version: '3'
services:
  db:
     image: bigpanda-db
     build: ${APP_ROOT:-.}/db
     restart: always
  web:
    image: bigpanda-app
    build: ${APP_ROOT:-.}
    depends_on:
    - db
    ports:
    - "${APP_PORT:-3000}:3000"
    restart: always
